Implement Risk Management Agent #6
SaudAltamimi/ValueMPT pull request #19
Opened 2024-08-15 14:47 UTC by balbanyan

Risk report generator using RiskAnalyzer class, including calculations for beta, systematic, and unsystematic risk

2024-08-20 07:33 UTC, balbanyan commented
Changes summary:

-Fixed an error where missing data was leading to misaligned dates (mismatch in lengths of datasets) before calculating the covariance. This error occurred when using tickers from TASI due to incomplete data.  dropna() function was not enough to resolve this issue, therefore I added an align() function to ensure both stock and market returns were aligned to the same dates.

-Added a time period to the risk assessment report generator

2024-08-23 16:25 UTC, SaudAltamimi requested changes
Overall it looks great. I just need three changes:

- [ ] Creating a notebooks example. In `notebooks/` folder outside `src/` folder
- [ ] remove dummy tickers from the same class file.
- [ ] Keep imports in the same python file

2024-08-23 16:25 UTC, SaudAltamimi commented on src/classes.py
> +from imports import *
I prefer to see the imports in the same file. It's easier to track.

2024-08-23 16:25 UTC, SaudAltamimi commented on src/classes.py
> +#Dummy variables
For testing the calss using dummy variables. I like to have them seperated in either unit tests or notebooks.

2024-09-04 21:19 UTC, SaudAltamimi requested changes
Can you just add the code inside a specific folder `src/value_mpt/risk`

2024-09-04 21:19 UTC, SaudAltamimi commented on src/classes.py
> +        self.start_date = self.end_date - timedelta(days = self.lookback_days)
Can you add the lookback period variable into the class variables. We might need to adjust it for expirmentation.

2024-09-04 21:19 UTC, SaudAltamimi commented on src/classes.py
> +        self.start_date = self.end_date - timedelta(days = self.lookback_days)
It's better for now to keep it `lookback_years`

2024-09-13 17:37 UTC, SaudAltamimi approved these changes

2024-09-13 17:41 UTC, merged